name = "max_bot"
version = "0.1.0"
description = "Gleam client library for Max messenger Bot API"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
envoy = ">= 1.2.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
